#!/usr/bin/env bash

mv "$MODULE_ROOT_DIRECTORY_PATH/.build/$MODULE_NAMESPACE_VALUE.js" "$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.js" &&	\
rm -rfv "$MODULE_ROOT_DIRECTORY_PATH/.build" || true;
